apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: bW9uZ291c2Vy # mongouser required field for kubernetes.io/basic-auth
  password: dDBwLVNlY3JldA== # t0p-Secret required field for kubernetes.io/basic-auth